apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-oidc
  namespace: jupyterhub
spec:
  secretStoreRef:
    name: keycloak
    kind: ClusterSecretStore
  target:
    name: jupyterhub-oidc
  data:
    - secretKey: JUPYTERHUB_OAUTH_CLIENT_ID
      remoteRef:
        key: keycloak-clients
        property: JUPYTERHUB_CLIENT_ID
    - secretKey: JUPYTERHUB_OAUTH_CLIENT_SECRET
      remoteRef:
        key: keycloak-clients
        property: JUPYTERHUB_CLIENT_SECRET
