apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-conf-custom
  namespace: kube-system
data:
  custom.conf: |
    rewrite stop {
      name exact cnoe.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
      name exact vault.cnoe.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
    }

