serviceName:  ${{values.name}}

namespace:  ${{values.name}}

hostName: ${{values.repoHost}}

giteaBaseUrl: ${{values.repoHost}}:443/gitea/giteaAdmin

imageBase: ${{values.repoHost}}:443/gitea/giteaadmin

envs:
{%- if (values.envConfig.length) %}
{%- set depends = 'None' %}
{%- for envDetails in values.envConfig %}
  - name: ${{ envDetails.environment }}
    depends: ${{ depends }}
    cluster: ${{ envDetails.clusterName }}
  {%- set depends = envDetails.environment %}
{%- endfor %}
{%- endif %}