apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-oidc
  namespace: monitoring
spec:
  secretStoreRef:
    name: keycloak
    kind: ClusterSecretStore
  target:
    name: grafana-oidc
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: keycloak-clients
        property: GRAFANA_CLIENT_ID
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: keycloak-clients
        property: GRAFANA_CLIENT_SECRET
