apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-platform-engineering-config
  namespace: ai-platform-engineering
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  # Minimal configuration to satisfy Helm template requirements
