apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-platform-engineering-helm-values
  namespace: ai-platform-engineering
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  additional-values.yaml: |
    global:
      llmSecrets:
        externalSecrets:
          target: "vault"
          enabled: false
