apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: "0.27.0"
      helm:
        valueFiles:
          - $values/ai-platform-engineering/vault/values.yaml
    - repoURL: https://github.com/cnoe-io/stacks.git
      targetRevision: main
      path: ai-platform-engineering/vault/manifests
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
