apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: "0.27.0"
      helm:
        values: |
          server:
            extraEnvironmentVars:
              VAULT_ADDR: 'https://cnoe.localtest.me:8443/vault'
              VAULT_UI_ADDR: 'https://cnoe.localtest.me:8443/ui'
    - repoURL: https://github.com/suwhang-cisco/stacks.git
      targetRevision: main
      path: ai-platform-engineering/vault/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
