apiVersion: v1
kind: ConfigMap
metadata:
  name: agentgateway-config
  namespace: agentgateway
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.yaml: |
    adminAddr:
      SocketAddr: "0.0.0.0:15000"
    statsAddr:
      SocketAddr: "0.0.0.0:15020"
    readinessAddr:
      SocketAddr: "0.0.0.0:15021"

