apiVersion: v1
kind: ConfigMap
metadata:
  name: agentgateway-config
  namespace: agentgateway
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.yaml: |
    binds:
    - port: 3000
      listeners:
      - routes:
        - policies:
            cors:
              allowOrigins:
                - "*"
              allowHeaders:
                - mcp-protocol-version
                - content-type
                - cache-control
          backends:
          - mcp:
              targets:
              - mcp:
                  host: weather.outshift.io
                  path: /mcp
                  port: 443
                name: weather

