apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name | dump}}
  namespace: argocd
  labels:
    example: basic
spec:
  project: default
  source:
    repoURL: ${{values.repoUrl | dump}}
    targetRevision: HEAD
    path: .
  destination:
    name: workshop
    namespace: ${{values.name | dump}}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
