apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: "{{ .Values.appName }}-{{ .Values.envName }}"
  labels:
    entity-id: {{ .Values.appName }}
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName }}