kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kyverno-pss-policies-audit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kyverno/kyverno
    targetRevision: 3.2.7
    path: charts/kyverno-policies
    helm:
      releaseName: "kyverno-policies"
      parameters:
        - name: "podSecurityStandard"
          value: restricted
        - name: "validationFailureAction"
          value: Audit
        - name: "podSecuritySeverity"
          value: High
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
    - Replace=true
    automated:
      selfHeal: true
    retry:
      limit: 30
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
