apiVersion: v1
kind: Service
metadata:
  name: agentgateway
  namespace: agentgateway
  labels:
    app: agentgateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
  - port: 15000
    targetPort: 15000
    protocol: TCP
    name: ui
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: proxy
  selector:
    app: agentgateway

