# This values file configures the official Vault Helm chart.

# Vault UI/API does not support domain subpathing - must use subdomain approach
# Using vault.cnoe.localtest.me instead of cnoe.localtest.me/vault
server:
  extraEnvironmentVars:
    VAULT_ADDR: 'https://vault.cnoe.localtest.me:8443'
    # Explicitly set VAULT_ADDR for internal use to localhost
    VAULT_ADDR_INTERNAL: 'http://127.0.0.1:8200'