apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hubble-ui
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: cnoe://hubble-ui-ingress
    targetRevision: HEAD
    path: "."
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated: {}
    
