apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'istio-system'
  namespace: argocd
spec:
  ignoreDifferences:
    # Allow users to modify mesh config if needed for testing
    - kind: ConfigMap
      group: ""
      name: istio
      jsonPointers:
        - /data
    # Kind issue
    - kind: ValidatingWebhookConfiguration
      group: "admissionregistration.k8s.io"
      jsonPointers:
        - /webhooks
  project: default
  sources:
    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.24.1
      helm:
        valuesObject:
          profile: ambient
      chart: cni
    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.24.1
      helm:
        valuesObject:
          profile: ambient
      chart: base
    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.24.1
      chart: ztunnel
      helm:
        valuesObject:
          profile: ambient
    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.24.1
      chart: istiod
      helm:
        valuesObject:
          profile: ambient
          meshConfig:
            defaultProviders:
              metrics:
                - prometheus
            enableTracing: true
            extensionProviders:
              - name: otel
                opentelemetry:
                  port: 4317
                  service: otel-opentelemetry-collector.observability.svc.cluster.local
                  resource_detectors:
                    environment: {}
    # Add Gateway API CRDs
    - repoURL: 'https://github.com/kubernetes-sigs/gateway-api/'
      targetRevision: v1.2.1
      path: ./config/crd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
