# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: gitea-credentials
#   namespace: {{ .Values.namespace }}
# spec:
#   secretStoreRef:
#     name: gitea
#     kind: ClusterSecretStore
#   refreshInterval: "0"
#   target:
#     name: gitea-credentials
#   data:
#     - secretKey: GITEA_USERNAME
#       remoteRef:
#         key: gitea-credential
#         property: username
#     - secretKey: GITEA_PASSWORD
#       remoteRef:
#         key: gitea-credential
#         property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-credentials
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    name: argocd
    kind: ClusterSecretStore
  refreshInterval: "0"
  target:
    name: argocd-credentials
  data:
    - secretKey: ARGOCD_ADMIN_PASSWORD
      remoteRef:
        key: argocd-initial-admin-secret
        property: password