apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 1.10.3
      helm:
        values: |
          fullnameOverride: tempo
          service:
            type: ClusterIP
      chart: tempo
    - repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 8.5.1
      helm:
        values: |
          env:
            GF_AUTH_ANONYMOUS_ENABLED: true
            GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
            GF_AUTH_DISABLE_LOGIN_FORM: true
          
          datasources:
            datasources.yaml:
              apiVersion: 1
          
              datasources:
                - name: Tempo
                  type: tempo
                  access: proxy
                  orgId: 1
                  url: http://tempo:3100
                  basicAuth: false
                  isDefault: true
                  version: 1
                  editable: false
                  apiVersion: 1
                  uid: tempo
                - name: Prometheus
                  type: prometheus
                  access: proxy
                  # Access mode - proxy (server in the UI) or direct (browser in the UI).
                  url: http://prometheus-server.observability.svc
                  jsonData:
                    httpMethod: POST
                    manageAlerts: true
                    prometheusType: Prometheus
                    prometheusVersion: 2.55.0
                    cacheLevel: 'High'
                    disableRecordingRules: false
                    incrementalQueryOverlapWindow: 10m
      chart: grafana
    - repoURL: cnoe://grafana
      targetRevision: HEAD
      # with path set to '.' and cnoe://manifests. we are wanting ArgoCD to sync from the ./manifests directory.
      path: "."
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: 'ambient'
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
