apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'istio-kiali'
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: cnoe://kiali
      targetRevision: HEAD
      path: "."
    - repoURL: 'https://kiali.org/helm-charts'
      targetRevision: v2.0.0
      path: 'kiali/kiali-operator'
      helm:
        valuesObject:
          cr:
            create: 'true'
            namespace: 'istio-system'
            spec:
              auth:
                strategy: 'anonymous'
              external_services:
                prometheus:
                  url: "http://prometheus-server.observability.svc"
                grafana:
                  enabled: true
                  internal_url: 'http://tempo-grafana.observability.svc'
                  # Public facing URL of Grafana
                  external_url: 'https://tracing.cnoe.localtest.me:8443/'
      chart: kiali-operator
