kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.2.7
    helm:
      releaseName: kyverno
      valuesObject:
          kyverno.fullname: kyverno
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    syncOptions:
    - Replace=true
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 30
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
