apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - command:
            - node
            - packages/backend
            - --config
            - config/app-config.yaml
          env:
            - name: LOG_LEVEL
              value: debug
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          envFrom:
            - secretRef:
                name: backstage-env-vars
            - secretRef:
                name: gitea-credentials
            - secretRef:
                name: argocd-credentials
          image: public.ecr.aws/cnoe-io/backstage:rc1
          name: backstage
          ports:
            - containerPort: 7007
              name: http
          volumeMounts:
            - mountPath: /app/config
              name: backstage-config
              readOnly: true
      serviceAccountName: backstage
      volumes:
        - name: backstage-config
          projected:
            sources:
              - configMap:
                  items:
                    - key: app-config.yaml
                      path: app-config.yaml
                  name: backstage-config
              - secret:
                  items:
                    - key: k8s-config.yaml
                      path: k8s-config.yaml
                  name: k8s-config