apiVersion: v1
kind: Secret
metadata:
  name: k8s-config
  namespace: backstage
stringData:
  k8s-config.yaml: "type: 'config'\nclusters:\n  - url: https://kubernetes.default.svc.cluster.local\n
    \   name: local\n    authProvider: 'serviceAccount'\n    skipTLSVerify: true\n
    \   skipMetricsLookup: true\n    serviceAccountToken: \n      $file: /var/run/secrets/kubernetes.io/serviceaccount/token\n
    \   caData: \n      $file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n"
