apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: ingress-nginx-cnoe-operation
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - ReplicaSet
        namespaces:
        - ingress-nginx
        names:
        - ingress-nginx*
